export const CCList = [
    'AE','AI','AQ','AR','AT','AU','AW','BB','BE','BD',
    'BG','BH','BM','BN','BR','BS','BW','CA','CD','CH',
    'CL','CN','CO','CR','CX','CY','CZ','DE','DK','EC',
    'EE','EG','ES','ET','FI','FJ','FR','GA','GB','GH',
    'GL','GR','HK','HR','HU','ID','IE','IL','IN','IT',
    'JM','JO','JP','KE','KR','KW','LI','LT','LU','LV',
    'MC','ME','MO','MT','MU','MV','MX','MY','NG','NL',
    'NO','NZ','PA','PE','PH','PK','PL','PR','RO','RS',
    'RU','SA','SC','SE','SG','SK','SM','TC','TH','TR',
    'TT','TW','UA','US','UY','VE','VG','VI','VN','ZA',
];

export const getFullCountryName = {
    AE: 'UNITED ARAB EMIRATES',
    AI: 'ANGUILLA',
    AQ: 'ANTARCTICA',
    AR: 'ARGENTINA',
    AT: 'AUSTRIA',
    AU: 'AUSTRALIA',
    AW: 'ARUBA',
    BB: 'BARBADOS',
    BE: 'BELGIUM',
    BD: 'BANGLADESH',
    BG: 'BULGARIA',
    BH: 'BAHRAIN',
    BM: 'BERMUDA',
    BN: 'BRUNEI',
    BR: 'BRAZIL',
    BS: 'BAHAMAS',
    BW: 'BOTSWANA',
    CA: 'CANADA',
    CD: 'DEMOCRATIC REPUBLIC OF CONGO',
    CH: 'SWITZERLAND',
    CL: 'CHILE',
    CN: 'CHINA',
    CO: 'COLOMBIA',
    CR: 'COSTA RICA',
    CX: 'CHRISTMAS ISLANDS',
    CY: 'CYPRUS',
    CZ: 'CZECH REPUBLIC',
    DE: 'GERMANY',
    DK: 'DENMARK',
    EC: 'ECUADOR',
    EE: 'ESTONIA',
    EG: 'EGYPT',
    ES: 'SPAIN',
    ET: 'ETHIOPIA',
    FI: 'FINLAND',
    FJ: 'FIJI',
    FR: 'FRANCE',
    GA: 'GABON',
    GB: 'GREAT BRITAIN',
    GH: 'GHANA',
    GL: 'GREENLAND',
    GR: 'GREECE',
    HK: 'HONG KONG',
    HR: 'CROATIA',
    HU: 'HUNGARY',
    ID: 'INDONESIA',
    IE: 'IRELAND',
    IL: 'ISRAEL',
    IN: 'INDIA',
    IT: 'ITALY',
    JM: 'JAMAICA',
    JO: 'JORDAN',
    JP: 'JAPAN',
    KE: 'KENYA',
    KR: 'REPUBLIC OF KOREA',
    KW: 'KUWAIT',
    LI: 'LIECHTENSTEIN',
    LT: 'LITHUANIA',
    LU: 'LUXEMBOURG',
    LV: 'LATVIA',
    MC: 'MONACO',
    ME: 'MONTENEGRO',
    MO: 'MACAO',
    MT: 'MALTA',
    MU: 'MAURITIUS',
    MV: 'MALDIVES',
    MX: 'MEXICO',
    MY: 'MALAYSIA',
    NG: 'NIGERIA',
    NL: 'NETHERLANDS',
    NO: 'NORWAY',
    NZ: 'NEW ZEALAND',
    PA: 'PANAMA',
    PE: 'PERU',
    PH: 'PHILIPPINES',
    PK: 'PAKISTAN',
    PL: 'POLAND',
    PR: 'PUERTO RICO',
    RO: 'ROMANIA',
    RS: 'SERBIA',
    RU: 'RUSSIAN FEDERATION',
    SA: 'SAUDI ARABIA',
    SC: 'SEYCHELLES',
    SE: 'SWEDEN',
    SG: 'SINGAPORE',
    SK: 'SLOVAKIA',
    SM: 'SAN MARINO',
    TC: 'TURKS AND CAICOS',
    TH: 'THAILAND',
    TR: 'TURKEY',
    TT: 'TRINIDAD TOBAGO',
    TW: 'TAIWAN',
    UA: 'UKRAINE',
    US: 'UNITED STATES OF AMERICA',
    UY: 'URUGUAY',
    VE: 'VENEZUELA',
    VG: 'BRITISH VIRGIN ISLANDS',
    VI: 'US VIRGIN ISLANDS',
    VN: 'VIETNAM',
    ZA: 'SOUTH AFRICA',
}